FROM node:21-alpine AS builder
WORKDIR /user/app

COPY package*.json ./
COPY turbo.json ./

#add all package .json consist in the fiel
RUN npm install

# COPY package.json package-lock.json turbo.json ./
COPY . .
RUN npm run build

FROM node:21-alpine 
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD [ "npm","run" ,"start-user-app"]