import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "MoneyBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link className="border-radius: 50%;"  rel="icon" type="image/svg+xml"
    href="https://e7.pngegg.com/pngimages/48/626/png-clipart-meli-bugeja-ltd-logo-brand-rosebrook-flooring-paints-ltd-blue-text.png" /></head>
      <Providers>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
