import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./Providers";
import GlobalBar from "./components/GlobalBar";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "MoneyBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link className="rounded-full h-3 w-3"  rel="icon" type="image/svg+xml"
    href="https://img.freepik.com/premium-vector/alphabet-letter-icon-logo-mb-bm_724865-195.jpg" /></head>
      <Providers>
        
        <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-950 `}>
          <div className="lg:block hidden">
          <GlobalBar/>
          {children}
          <Toaster richColors/>
          </div>
          <div className="flex justify-center items-center h-screen text-blue-600  lg:hidden text-3xl border-2 border-slate-400">
                ONLY FOR DESKTOP
          </div>
        </body>
      </Providers>
    </html>
  );
}
